
version: '3'

networks:
  nextcloud_network:

services:
  nextcloud:
    image: nextcloud
    depends_on:
      - nextcloud-db           # If using MySQL
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=America/Argentina/Buenos_Aires
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=Paris1984
      - DB_HOST=nextcloud-db
    volumes:
      - /home/opensuse/docker/nextcloud/data:/var/www/html/

    ports:
      - 1080:80
      - 1443:443
    networks:
      - nextcloud_network
    restart: unless-stopped

  # If using MySQL
  nextcloud-db:
    image: mariadb
    volumes:
      - /docker/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Paris1984
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=Paris1984
    networks:
      - nextcloud_network
    ports:
      - 3306:3306
    restart: unless-stopped
